### ISSUE TITLE
should update to sdk v2  ?

### ISSUE THREAD

**Issue by stayliv3** [aws-samples/aws-iot-device-defender-agent-sdk-python#19]
it seems does not work now .

2020-06-15 04:31:52,432 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Connect timed out
Traceback (most recent call last):
  File "agent.py", line 174, in <module>
    main()
  File "agent.py", line 140, in main
    iot_client.connect()
  File "agent.py", line 77, in connect
    self.iot_client.connect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 513, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 199, in connect
    raise connectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException

**Comment by stayliv3** [comment]
python v2

**Comment by saideepbollam** [comment]
Hi,

AWSIoTDeviceDefenderAgentSDK is compatible with AWSIoTPythonSDK (v1.x).

From the exception log, it appears that the agent timedout establishing a connection to AWS IoT. This could happen if the certificate being used does not have an associated policy or the policy not granting the required permissions, [Authorization](https://docs.aws.amazon.com/iot/latest/developerguide/iot-policies.html) section of the developer guide has the steps to configure the required policies.

Additionally, AWS IoT logs can be enabled by following the [Logging and Monitoring](https://docs.aws.amazon.com/iot/latest/developerguide/security-logging.html) guide. [AWS IoT CloudWatch logs](https://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html), if enabled with the required logging level, will log the status of each request made to AWS IoT.

Please let us know if the issue persists.

**Comment by stayliv3** [comment]
thanks for your guide. the problem is the security ploicy .I am new to aws iot and don't know the rule.  it works now . thanks again！
